using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Take.Blip.Builder.Diagnostics
{
    /// <summary>
    /// Represents a trace of a state in the monitoring process, including actions, outputs, and extension data.
    /// </summary>
    public class StateTrace : Trace
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StateTrace"/> class, setting up collections for actions and outputs.
        /// </summary>
        public StateTrace()
        {
            Id = Guid.NewGuid().ToString();
            InputActions = new List<ActionTrace>();
            OutputActions = new List<ActionTrace>();
            Outputs = new List<OutputTrace>();
            AfterStateChangedActions = new List<ActionTrace>();
            LocalCustomActions = new List<ActionTrace>();
        }

        /// <summary>
        /// Gets or sets the unique identifier of the state.
        /// </summary>
        [DataMember(Name = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the collection of input actions performed in this state.
        /// </summary>
        [DataMember(Name = "inputActions")]
        public ICollection<ActionTrace> InputActions { get; set; }

        /// <summary>
        /// Gets or sets the collection of output actions performed in this state.
        /// </summary>
        [DataMember(Name = "outputActions")]
        public ICollection<ActionTrace> OutputActions { get; set; }

        /// <summary>
        /// Gets or sets the collection of outputs generated by this state.
        /// </summary>
        [DataMember(Name = "outputs")]
        public ICollection<OutputTrace> Outputs { get; set; }

        /// <summary>
        /// Gets or sets the extension data for this state, allowing for additional custom information.
        /// </summary>
        [DataMember(Name = "extensionData")]
        public IDictionary<string, JToken> ExtensionData { get; set; }

        [DataMember(Name = "afterStateChangedActions")]
        public ICollection<ActionTrace> AfterStateChangedActions { get; set; }

        [DataMember(Name = "localCustomActions")]
        public ICollection<ActionTrace> LocalCustomActions { get; set; }
    }
}
